# Generated by Django 3.0.8 on 2020-08-05 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ref',
            new_name='href',
        ),
    ]
