# Generated by Django 3.0.8 on 2020-08-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapp',
            name='ref',
            field=models.CharField(default='lyric-cloud/', max_length=63),
            preserve_default=False,
        ),
    ]
